### PR TITLE
Remove use of scala.concurrent.forkjoin

### LINKED ISSUE #191: 2.13 regression: needs update for forkjoin removal
since https://github.com/scala/scala/pull/6319 was merged, in the 2.13 community build we see:

```
[scala-async] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.11/project-builds/scala-async-84e9cc9153c08a616cd7ea17bda6bb38f890303b/src/test/scala/scala/async/run/futures/FutureSpec.scala:38: object forkjoin is not a member of package concurrent
[scala-async] [error]       implicit val ec = scala.concurrent.ExecutionContext.fromExecutor(new scala.concurrent.forkjoin.ForkJoinPool(), {
[scala-async] [error]                                                                                             ^
```

### PR DESCRIPTION
**Pull request by NthPortal**
Fixes #191

### CODE REVIEW

**Comment by NthPortal** [comment]
It looks like this is failing because `ForkJoinPool` didn't exist in Java 6. How did this actually ever work with Java 6?

**Comment by retronym** [comment]
The failure is the the (2.11.12 / JDK6) entry in the cross building matrix. I'm happy to drop support for Java 6 as a solution for this.

**Comment by NthPortal** [comment]
I note that removing that line from `build.sbt` leaves no mapping from 2.11 to `true`

**Comment by retronym** [comment]
We could switch the 2.11 build to use java 8

**Comment by SethTisue** [comment]
thank you

**Pull request merged**
