### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by Philippus**
Applying this PR will reduce the compile warnings from 82 to 15, see #197

### CODE REVIEW

**Comment by SethTisue** [comment]
LGTM, but let's let @retronym do the final review/merge

**Comment by retronym** [comment]
/cc @adriaanm is working on a fork of all this code that makes it use `scala.reflect.internal` APIs rather than `scala.reflect.api`.

I think in the meantime we should go ahead and merge this PR, but I'll let Adriaan comment.

Thanks for picking this up. I really should have done this when I dropped 2.10 support from this branch.

**Comment by SethTisue** [comment]
thanks @Philippus, really nice to have this code modernized.

**Comment by som-snytt** [comment]
BTW, `if (value == ())` no longer warns, though extra parens are benign.

**Pull request merged**
