### PR TITLE
drop support for Scala 2.11 as of 0.10.0

### PR DESCRIPTION
**Pull request by SethTisue**
also upgrade Scala 2.12.4 -> 2.12.6

### CODE REVIEW

**Comment by SethTisue** [comment]
@retronym the motivation here is to pave the way to move to sbt 1 by dropping Java 7 support

**Comment by SethTisue** [comment]
if this is merged, at the same time we'll need to the create a new `2.11.x` which README.md references

**Comment by SethTisue** [comment]
the issue of sbt 1 support is being discussed at https://github.com/scala/sbt-scala-module/issues/32

here in this repo, there's no great need to be on sbt 1. so Jason, I guess this basically depends on whether you consider dropping 2.11 support to be a nice simplification that would make your life in this repo easier.

**Comment by retronym** [comment]
Thanks. Agree the time is right.

This will simplify #194, as no longer have to avoid using Java SAMs.

**Comment by retronym** [comment]
> if this is merged, at the same time we'll need to the create a new 2.11.x branch, which README.md references

Done: https://github.com/scala/scala-async/tree/2.11.x

**Comment by SethTisue** [comment]
2.11 community build updated: https://github.com/scala/community-builds/commit/20a94d95346eb688d341fe5f174a38aa6aac15e7

**Pull request merged**
